spring:
  application:
    name: remember
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/remember_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  threads:
    virtual:
      enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    shutdown:
      enabled: true